[build]
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/total"
  to = "/.netlify/functions/total"
  status = 200

[[redirects]]
  from = "/api/stripe-webhook"
  to = "/.netlify/functions/stripe-webhook"
  status = 200
